site_name: GeoBlacklight Documentation
site_url: https://geoblacklight.org/docs
#repo_url: https://github.com/geoblacklight/docs
theme: 
     name: readthedocs
     logo: img/geoblacklight-logo-small@2x.png
     extra_css: docs/extra.css
     highlightjs: true
     titles_only: true
     include_homepage_in_sidebar: false

extra_css:
  - extra.css
nav:
- Overview:
     - 'What is GeoBlacklight': '1. overview/what_is_geoblacklight.md'
     - 'Contributing to GeoBlacklight': '1. overview/contributing.md'
- Installation:
     - 'Quick Start': '2. installation/geoblacklight_quick_start.md'
     - 'Getting Started - Developers Guide': '2. installation/getting_started_developers.md'
- Customization:
     - 'Adding Leaflet Controls': '3. customization/adding_leaflet_controls.md'
     - 'Configuring Leaflet for Retina Displays': '3. customization/leaflet_retina_configuration.md'
     - 'Using the Data Relations Widget': '3. customization/data_relations_widget.md'
     - 'Configuring Index Maps': '3. customization/index_maps.md'
     - 'Switching Default Basemap': '3. customization/default_basemap.md'
     - 'Adding Support for Item Images': '3. customization/item_images.md'
     - 'Adding Mirador IIIF Manifest Viewer': '3. customization/adding_mirador_viewer.md'
     - 'Accessing Raster and Vector Layers in GeoPackages': '3. customization/accessing_geopackages.md'
     - 'Adding SVG Icons': '3. customization/adding_svg_icons.md'
     - 'Rendering Line Breaks or HTML from the Description Field': '3. customization/rendering_html_from_description.md'
- Upgrading:
     - 'Upgrading to Version 4.0': '4. upgrading/Upgrading_to_version_4_0.md'
     - 'Upgrading to Version 2.0': '4. upgrading/Upgrading_to_version_2_0.md'
- Tutorials:
     - 'Tutorials': 'tutorials/tutorials.md'

